# Generated by Django 4.0.5 on 2022-06-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecsValueMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_id', models.CharField(max_length=100)),
                ('model_id', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('use_flag', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2)),
            ],
        ),
    ]
