# Generated by Django 4.0.5 on 2022-06-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTL', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specsvaluemap',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specsvaluemap',
            name='spec_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
